version: "3.8"
services:
  db:
    image: postgres:16
    container_name: propertyfish-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: propertyfish
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d propertyfish"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: {}
